name: Pylint Test

on: [push]

jobs:
  Test-github-actions:
    runs-on: ubuntu-latest
    steps:
      - run: python --version
      
  pylint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint Flask

      - name: Set PYTHONPATH
        run: export PYTHONPATH="${PYTHONPATH}:${PWD}"

      - name: Run Pylint
        run: pylint app.py
        continue-on-error: true